[tool.black]
line-length = 79
skip-string-normalization=true
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.docformatter]
recursive = true
wrap-summaries = 79
wrap-descriptions = 79
blank = true
